name: Basic Workflow
on:
  push:
    branches: feature/basic-workflow
jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest
    steps:
    - name: The Thing I've Done
      run: echo "I've done a thing in ${{ github.ref }} branch!"
    - name: Set Summary
      run: echo "I've done a thing in ${{ github.ref }} branch!" >> $GITHUB_STEP_SUMMARY
